// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getLRT_cpp
Rcpp::List getLRT_cpp(arma::mat Y, int p, int q, double eps, arma::mat Mean);
RcppExport SEXP _NPCovSepTest_getLRT_cpp(SEXP YSEXP, SEXP pSEXP, SEXP qSEXP, SEXP epsSEXP, SEXP MeanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Mean(MeanSEXP);
    rcpp_result_gen = Rcpp::wrap(getLRT_cpp(Y, p, q, eps, Mean));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NPCovSepTest_getLRT_cpp", (DL_FUNC) &_NPCovSepTest_getLRT_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_NPCovSepTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
