# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name getLRT
#' @title Compute the LRT using Dutilleul (1999)'s Algorithm
#' @description This function implements Dutilleul (1999)'s Algorithm to obtain the likelihood ratio test statistic under normality. The null hypothesis is the separabiliy of covariance matrix, i.e. \eqn{\Sigma}=\code{U} \eqn{\otimes} \code{V}, and the alternative is not the null.
#' @param Y A r-by-(\code{p}*\code{q}) matrix where r is the sample size. See `Details' in \code{\link{Min_PermTest}} for its form.
#' @param p,q The number of rows and columns for matrix-variate data.
#' @param eps Tolerance constant for convergence. Default is 1e-10.
#' @param Mean The mean matrix of \code{Y}. Default is the sample mean vector for each row.
#' @return A list with components:
#' \item{lrt}{The LRT statistic.}
#' \item{U}{Row-wise covariance (p-by-p).}
#' \item{V}{Column-wise covariance (q-by-q).}
#' @references Dutilleul, P. (1999). The mle algorithm for the matrix normal distribution. \emph{Journal of Statistical Computation and Simulation}, \strong{64(2)}, 105-123.
#' @seealso \code{\link{Min_PermTest}}
#' @export
getLRT_cpp <- function(Y, p, q, eps, Mean) {
    .Call('_NPCovSepTest_getLRT_cpp', PACKAGE = 'NPCovSepTest', Y, p, q, eps, Mean)
}

